import { useEffect, useState } from 'react';
import { Activity, ArrowUpRight, Cpu, Database, FlaskConical, HardDrive, Radio, ShieldCheck, Wifi, WifiOff, Zap, ChevronRight, Clock, AlertTriangle } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import type { State, Reading } from './main';
import './command.css';
import Experiment from './Experiment';

type Operations = {
  runtime: {cpu_percent:number|null; rss_bytes:number|null; processing_p95_ms:number|null; processing_samples:number; memory_budget_mb:number; readings_per_second:number; uptime_seconds:number; offline_readings:number; offline_critical:number};
  bandwidth:{bytes_per_second:number; paced:boolean; wait_seconds:number; burst_bytes:number};
  queue_by_priority:{priority:number;count:number;bytes:number}[];
  retained_readings:number; oldest_pending_seconds:number;
  timeline:{at:number;kind:string;detail:string}[];
  recent_events:{id:string;machine:string;kind:string;status:string;priority:number;created:number;acknowledged:number|null;bytes:number}[];
  lab:{status:string;scenario:string|null;machine:string|null;sent:number;seconds:number;error:string|null;ml_enabled?:boolean};
};
const units:Record<string,string>={temperature:'°C',vibration:'mm/s',pressure:'bar',current:'A',rpm:'RPM'};
const byte=(n:number)=>n>=1048576?(n/1048576).toFixed(1)+' MiB':n>=1024?(n/1024).toFixed(1)+' KiB':Math.round(n)+' B';
const at=(n:number)=>new Date(n*1000).toLocaleTimeString();
const pretty=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const priority=['Routine summary','Incident evidence','Warning / operator update','Critical notification'];
function useOperations(accessKey:string){
 const [ops,setOps]=useState<Operations|null>(null);const [error,setError]=useState('');
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;const ctrl=new AbortController();
 async function poll(){try{const r=await fetch('/api/operations',{headers:{'X-API-Key':accessKey},signal:ctrl.signal});if(!r.ok)throw Error('Operations feed unavailable ('+r.status+')');const body=await r.json();if(active){setOps(body);setError('');}}catch(e){if(active)setError(String(e));}if(active)timer=setTimeout(poll,1500);}
 void poll();return()=>{active=false;ctrl.abort();clearTimeout(timer);};},[accessKey]);return{ops,error};
}
function Meter({value,max,tone='mint'}:{value:number;max:number;tone?:string}){return <div className={'cc-meter '+tone}><span style={{width:Math.min(100,Math.max(0,value/max*100))+'%'}}/></div>}

type Props={accessKey:string;state:State;history:Reading[];selected:string;select:(id:string)=>void;navigate:(tab:string)=>void;incident:(id:string)=>void};
export default function CommandCenter({accessKey,state,history,selected,select,navigate,incident}:Props){
 const {ops,error}=useOperations(accessKey);const [sensor,setSensor]=useState('temperature');
 const machine=state.machines.find(m=>m.id===selected);const fresh=state.machines.filter(m=>!m.stale);
 const incomplete=state.machines.filter(m=>Object.values(m.quality).some(q=>q!=='VALID')).length;
 const incidents=state.incidents.filter(i=>!['CLOSED','RECOVERED'].includes(i.status));const critical=incidents.filter(i=>i.severity==='CRITICAL');
 const offline=state.connection.status==='OFFLINE';const processed=state.counters.readings_processed||0;
 const baseline=state.counters.baseline_payload_bytes||0;const uploaded=state.counters.attempted_payload_bytes||0;
 const delta=baseline?(1-uploaded/baseline)*100:null;
 const chart=history.slice(-60).map(r=>({time:at(r.timestamp),raw:r.quality[sensor]==='VALID'?r.values[sensor]:null,filtered:r.filtered?.[sensor]??null}));
 const queuedBytes=ops?.queue_by_priority.reduce((n,g)=>n+g.bytes,0)||0;
 const evidence=[
 ['01','Noisy & incomplete streams',incomplete?`${incomplete} machines with degraded or stale data`:'Inspect raw / filtered values and quality flags',processed?'Live evidence':'Awaiting telemetry','Machine'],
 ['02','Local anomaly detection',state.model.status==='AVAILABLE'?`Rules + ${state.model.source_type||'local'} ML`:'Rules active · ML not calibrated',state.model.status==='AVAILABLE'?'Model loaded':'Rules only','Machine'],
 ['03','Urgency classification',`${critical.length} critical · ${incidents.length-critical.length} warning / other active incidents`,incidents.length?'Observed':'Awaiting incident','Incidents'],
 ['04','Transmission reduction',delta===null?'Collect readings to compare payload bytes':`${Math.abs(delta).toFixed(1)}% ${delta>=0?'less':'more'} upload payload than raw baseline`,delta!==null?'Measured':'Awaiting data','Data Flow'],
 ['05','Detection through an outage',`${ops?.runtime.offline_critical||0} critical readings processed while cloud was offline`,ops?.runtime.offline_critical?'Observed this session':'Exercise in lab','Scenario Lab'],
 ['06','Durable local buffer',`${state.pending} events · ${byte(queuedBytes)} queued payload`,state.pending?'Buffered':'Buffer available','Delivery'],
 ['07','Sync & recovery',`${state.counters.events_delivered||0} acknowledged events · ${state.counters.retry_failures||0} failed attempts`,'Inspect receipts','Data Flow'],
 ['08','Edge resource constraints',`${ops?byte(ops.bandwidth.bytes_per_second)+'/s upload budget':'Measuring'} · bounded storage`,'Measured + configured','Delivery']
 ];
 return <div className="cc">
  <div className={'cc-hero '+(offline?'is-offline':'')}><div><div className="cc-kicker"><span/> EDGE INTELLIGENCE · OPERATIONS</div><h2>{offline?'Cloud link interrupted. Local monitoring continues.':'One system. Every decision visible.'}</h2><p>{offline?'Accepted readings still pass through local detection and SQLite. Important events remain queued until the cloud acknowledges them.':'Follow telemetry from sensor quality checks to local decisions, preserved evidence and confirmed cloud delivery.'}</p><div className="cc-hero-chips"><span><Radio size={14}/>{fresh.length} / {state.machines.length} machines reporting</span><span>{offline?<WifiOff size={14}/>:<Wifi size={14}/>}Cloud {pretty(state.connection.status)}</span><span><Cpu size={14}/>{state.model.status==='AVAILABLE'?'Local ML available':'Rules active · ML uncalibrated'}</span></div></div><button onClick={()=>navigate('Scenario Lab')}><FlaskConical size={18}/>Open Scenario Lab<ArrowUpRight size={16}/></button></div>
  {error&&<div role="alert" className="cc-error">{error}. Last displayed measurements may be outdated.</div>}
  {ops?.lab.status==='RUNNING'&&<div className="cc-lab-strip"><FlaskConical size={17}/><strong>Synthetic source running</strong><span>{pretty(ops.lab.scenario||'')} · {ops.lab.machine} · {ops.lab.sent}/{ops.lab.seconds} readings</span><button onClick={()=>{if(ops.lab.machine)select(ops.lab.machine);}}>Inspect lab machine</button></div>}
  <div className="cc-path">
   {[[Radio,'01','Receive',processed.toLocaleString()+' readings','Cumulative local processing','Machine'],[ShieldCheck,'02','Validate',incomplete+' degraded machines','Missing / invalid / stale visible','Machine'],[Cpu,'03','Decide',incidents.length+' active incidents','Critical now · warnings debounce','Incidents'],[Database,'04','Preserve',(ops?.retained_readings??0)+' raw records',state.pending+' durable outgoing events','Data Flow'],[offline?WifiOff:Wifi,'05','Synchronise',pretty(state.connection.status),state.connection.last_success?'Last contact '+at(state.connection.last_success):'Waiting for cloud contact','Delivery']].map(([Icon,num,title,value,detail,target])=>{const I=Icon as typeof Radio;return <button key={String(num)} onClick={()=>navigate(String(target))} className={num==='05'&&offline?'cc-path-offline':''}><div><I size={18}/><small>{String(num)}</small></div><h3>{String(title)}</h3><strong>{String(value)}</strong><p>{String(detail)}</p></button>})}
  </div>
  <div className="cc-main-grid">
   <section className="cc-card cc-signal"><div className="cc-card-head"><div><span className="cc-eyebrow">SIGNAL INSPECTION</span><h3>What the edge actually sees</h3></div><div className="cc-selects"><select aria-label="Inspect machine" value={selected} onChange={e=>select(e.target.value)}><option value="" disabled>Select machine</option>{state.machines.map(m=><option key={m.id}>{m.id}</option>)}</select><select aria-label="Inspect sensor" value={sensor} onChange={e=>setSensor(e.target.value)}>{Object.entries(units).map(([s,u])=><option value={s} key={s}>{s} · {u}</option>)}</select></div></div>
   <div className="cc-signal-values"><div><small>Latest raw value</small><strong>{machine?.latest?.quality[sensor]==='VALID'&&!machine.stale?machine.latest.values[sensor]?.toFixed(sensor==='rpm'?0:2):'—'} <span>{units[sensor]}</span></strong></div><div><small>Recorded sensor quality</small><strong className="cc-small-value">{machine?.quality[sensor]||'AWAITING DATA'}</strong></div><div><small>Rule limits</small><strong className="cc-small-value">{machine?.limits[sensor]?.join(' / ')||'—'} <span>{units[sensor]}</span></strong></div></div>
   {chart.length?<div className="cc-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e4eaf1"/><XAxis dataKey="time" minTickGap={65} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={['auto','auto']} tick={{fontSize:10}} width={45} axisLine={false} tickLine={false}/><Tooltip/><Line name="Raw sensor" type="linear" dataKey="raw" stroke="#a1afc0" strokeWidth={1.7} dot={false} connectNulls={false} isAnimationActive={false}/><Line name="Causal median (ML input)" type="linear" dataKey="filtered" stroke="#168a72" strokeWidth={2.5} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<div className="cc-empty"><Activity/><strong>Waiting for a sensor stream</strong><p>Connect an equipment publisher or start a labelled synthetic scenario.</p><button onClick={()=>navigate('Scenario Lab')}>Start in Scenario Lab <ArrowUpRight size={14}/></button></div>}
   <div className="cc-chart-note"><span><i className="raw"/>Raw measurement</span><span><i/>Five-sample causal median</span><p>Rules use fresh raw values immediately. ML uses the median when all five sensors are valid. Gaps stay visible. {machine?.stale?'This stream is stale; chart shows saved history.':''}</p></div></section>
   <section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">LOCAL FIRST</span><h3>Incident response</h3></div><span className={'cc-pill '+(critical.length?'danger':'')}>{incidents.length} active</span></div>
   <div className="cc-incidents">{incidents.length?incidents.slice(0,3).map(i=><button key={i.id} onClick={()=>incident(i.id)}><div><span className={'cc-pill '+(i.severity==='CRITICAL'?'danger':'amber')}>{i.severity}</span><small>{at(i.opened_at)}</small></div><strong>{i.machine}</strong><p>{i.reasons.map(r=>r.source==='rule'?`${r.sensor} ${r.value} ≥ ${r.threshold}`:'ML found an unusual sensor pattern').join(' · ')}</p><div><span>{pretty(i.status)} · {i.capture_complete?'evidence captured':'capturing evidence'}</span><ChevronRight size={16}/></div></button>):<div className="cc-quiet"><ShieldCheck size={28}/><strong>No active incidents</strong><p>{fresh.length?'Monitoring incoming readings.':'No fresh equipment data; this is not a healthy-machine confirmation.'}</p></div>}</div>
   <div className="cc-offline-proof"><WifiOff size={18}/><div><strong>{ops?.runtime.offline_readings||0} readings processed during an outage</strong><p>{ops?.runtime.offline_critical||0} were critical · current process session</p></div></div></section>
  </div>
  <div className="cc-three-grid">
   <section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">SEND LESS, KEEP CONTEXT</span><h3>Cloud payload accounting</h3></div><ArrowUpRight size={18}/></div><div className="cc-accounting"><strong className="cc-big">{delta===null?'—':Math.abs(delta).toFixed(1)+'%'}<small>{delta===null?'Awaiting data':delta>=0?'less upload payload':'more upload payload'}</small></strong><p>Actual upload attempts compared with sending every raw reading. Includes incident evidence and retries.</p><label>Raw baseline <b>{byte(baseline)}</b></label><Meter value={baseline} max={Math.max(baseline,uploaded,1)} tone="slate"/><label>Attempted upload <b>{byte(uploaded)}</b></label><Meter value={uploaded} max={Math.max(baseline,uploaded,1)} tone={delta!==null&&delta<0?'amber':'mint'}/><label>Uncompressed attempts (compression accounting) <b>{byte(state.counters.compression_input_bytes||0)}</b></label><label>Transmitted attempts (compression accounting) <b>{byte(state.counters.compression_output_bytes||0)}</b></label><label>Superseded routine summaries <b>{state.counters.routine_events_superseded||0}</b></label><label>Retry traffic since this update <b>{byte(state.counters.retry_payload_bytes||0)}</b></label><small>Lifetime counters · payload bytes only. Short incident-heavy runs can send more. Normal operation is summarised about every 15 seconds.</small><button onClick={()=>navigate('Data Flow')}>Inspect actual summaries <ArrowUpRight size={14}/></button></div></section>
   <section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">DURABLE OUTBOX</span><h3>What gets sent first</h3></div><Database size={18}/></div><div className="cc-queue"><strong className="cc-big">{state.pending}<small>pending events · {byte(queuedBytes)}</small></strong>{[3,2,1,0].map(p=>{const g=ops?.queue_by_priority.find(x=>x.priority===p);return <div key={p}><label><span className={'cc-priority p'+p}>P{p}</span>{priority[p]}<b>{g?.count||0}</b></label><Meter value={g?.count||0} max={Math.max(1,state.pending)} tone={p===3?'red':'mint'}/></div>})}<p>Oldest pending: {Math.round(ops?.oldest_pending_seconds||0)}s · {state.pending}/{state.limits.queue} queue slots</p><small>Unattempted routine summaries are replaced by the latest per machine; older coverage is lost and counted. Routine events are evicted first under pressure. If important events fill the queue, ingestion returns backpressure.</small></div></section>
   <section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">RESOURCE ENVELOPE</span><h3>Measured at the edge</h3></div><Cpu size={18}/></div><div className="cc-resources"><label>Process CPU <b>{ops?.runtime.cpu_percent==null?'—':ops.runtime.cpu_percent.toFixed(1)+'%'}</b></label><Meter value={ops?.runtime.cpu_percent||0} max={100}/><label>Resident memory <b>{ops?.runtime.rss_bytes==null?'Unavailable':byte(ops.runtime.rss_bytes)}</b></label><Meter value={ops?.runtime.rss_bytes||0} max={(ops?.runtime.memory_budget_mb||512)*1048576}/><div className="cc-resource-pair"><div><small>Processing p95</small><strong>{ops?.runtime.processing_p95_ms==null?'—':ops.runtime.processing_p95_ms.toFixed(1)+' ms'}</strong></div><div><small>Readings / second</small><strong>{ops?.runtime.readings_per_second.toFixed(1)??'—'}</strong></div></div><label>Upload budget <b>{byte(ops?.bandwidth.bytes_per_second||32768)}/s</b></label><span className="cc-pill">{ops?.bandwidth.paced?'Pacing · '+ops.bandwidth.wait_seconds.toFixed(1)+'s wait':'Ready for next payload'}</span><small>CPU/RAM observed on native runs; Compose caps 1 CPU / 512 MiB. Processing includes validation, detection and SQLite; last 256 attempts. Upload pacing allows one event burst (max 256 KiB).</small></div></section>
  </div>
  <div className="cc-main-grid"><section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">REQUIREMENT EVIDENCE</span><h3>Eight requirements, inspectable behaviour</h3></div><ShieldCheck size={18}/></div><div className="cc-evidence">{evidence.map(([n,title,detail,status,target])=><button key={n} onClick={()=>navigate(target)}><span>{n}</span><div><strong>{title}</strong><p>{detail}</p><small>{status}</small></div><ChevronRight size={15}/></button>)}</div></section><section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">SYSTEM JOURNAL</span><h3>Failure & recovery timeline</h3></div><Clock size={18}/></div><div className="cc-timeline">{ops?.timeline.length?ops.timeline.slice(0,7).map((e,i)=><div key={e.at+'-'+i}><i className={e.kind.includes('OFFLINE')?'bad':''}/><small>{at(e.at)}</small><strong>{pretty(e.kind)}</strong><p>{e.detail}</p></div>):<p>Connection transitions and scenario actions appear here as they happen.</p>}</div></section></div>
 </div>;
}

export function ScenarioLab({accessKey,state,navigate,select}:{accessKey:string;state:State;navigate:(tab:string)=>void;select:(id:string)=>void}){
 const {ops,error}=useOperations(accessKey);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function act(path:string,body:unknown){setBusy(true);setMessage('');try{const r=await fetch('/api/testing/'+path,{method:'POST',headers:{'X-API-Key':accessKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Request rejected');if(d.machine)select(d.machine);setMessage(path==='scenario'?'Synthetic source started. Open Operations to watch the signal and incident.':path==='cloud'?'Cloud control applied. Watch the measured link status and queue.':'Control applied.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const enabled=state.fault_controls;const running=ops?.lab.status==='RUNNING';
 const choices=[['normal','Normal operation','Watch raw readings become periodic summaries.'],['noisy_normal','Sensor noise','Compare the raw signal with the causal median.'],['missing','Missing vibration','See quality degrade and ML pause rather than invent values.'],['critical','Critical machine event','At 15 seconds, temperature and vibration cross critical limits.'],['subthreshold','Below-threshold anomaly','Requires calibrated synthetic ML to detect unusual values below rule limits.'],['healthy_shift','Healthy operating shift','Observe a known ML limitation: unfamiliar healthy operation can trigger warnings.']];
 return <div className="cc"><div className="cc-hero"><div><div className="cc-kicker"><FlaskConical size={16}/> CONTROLLED SYSTEM EXERCISES</div><h2>Put the architecture under pressure.</h2><p>These controls generate labelled synthetic readings and cause real cloud request failures. Detection, database writes, incident handling and delivery use the working backend.</p></div><button onClick={()=>navigate('Overview')}>Watch operations <ArrowUpRight size={16}/></button></div>
 {!enabled&&<div className="cc-enable"><AlertTriangle size={20}/><div><strong>Scenario controls are disabled</strong><p>Set <code>EDGEGUARD_ENABLE_FAULTS=1</code> in your .env file and restart both services. Real equipment ingestion remains available without these controls.</p></div></div>}
 {(message||error)&&<div role="status" className="cc-enable">{message||error}</div>}
 <div className="cc-lab-strip"><Activity size={18}/><strong>{ops?.lab.status||'IDLE'}</strong><span>{ops?.lab.machine||'No synthetic source'} · {ops?.lab.sent||0}/{ops?.lab.seconds||120} samples</span><button disabled={!enabled||!running||busy} onClick={()=>act('stop',{})}>Stop source</button></div>
 {ops?.lab.error&&<p className="cc-error">Source stopped: {ops.lab.error}</p>}
 <Experiment accessKey={accessKey} enabled={enabled}/>
 <div className="cc-main-grid"><section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">01 / CHOOSE A STREAM</span><h3>Reproducible 120-second scenarios</h3></div></div><div className="cc-scenarios">{choices.map(([id,title,desc])=><button key={id} disabled={!enabled||running||busy||(id==='subthreshold'&&state.model.source_type!=='synthetic')} onClick={()=>act('scenario',{scenario:id,seconds:120})}><span><Activity size={19}/><ArrowUpRight size={15}/></span><strong>{title}</strong><p>{desc}</p><small>{id==='subthreshold'&&state.model.source_type!=='synthetic'?'Run scripts.setup_ml first':'Start scenario'}</small></button>)}</div><p className="cc-lab-note">Uses the synthetic model’s bound machine when available; otherwise LAB-01 with rules. Never feeds a model marked as real-equipment calibrated. Stop terminal publishers targeting the same machine before starting a lab stream. Existing unclosed incidents may reopen.</p></section>
 <section className="cc-card"><div className="cc-card-head"><div><span className="cc-eyebrow">02 / BREAK THE CLOUD LINK</span><h3>Exercise the reliability boundary</h3></div><WifiOff size={18}/></div><div className="cc-lab-controls"><p>Start a critical scenario. Once the incident appears, disconnect cloud ingestion. Acknowledge it locally, then restore the link and inspect the receipts.</p><button disabled={!enabled||busy} className="cc-danger-button" onClick={()=>act('cloud',{mode:'offline'})}><WifiOff size={18}/>Disconnect cloud ingestion</button><button disabled={!enabled||busy} onClick={()=>act('cloud',{mode:'online'})}><Wifi size={18}/>Restore cloud connection</button><button disabled={!enabled||busy} onClick={()=>act('cloud',{mode:'lose_ack'})}><Database size={18}/>Lose the next acknowledgement</button><p>“Lose acknowledgement” commits the next cloud event but returns an error. The edge retries the same ID; the cloud deduplicates it.</p><label>Upload budget<select aria-label="Upload budget" disabled={!enabled||busy} value={ops?.bandwidth.bytes_per_second||32768} onChange={e=>act('bandwidth',{bytes_per_second:Number(e.target.value)})}>{[4096,8192,32768,131072].map(b=><option key={b} value={b}>{byte(b)}/s payload</option>)}</select></label><small>Changes apply to subsequent sends for this process session. Ingestion and detection continue while upload pacing waits. Network controls leave the cloud UI reachable.</small></div></section></div>
 <div className="cc-walkthrough">{[['1','Observe','First 15 seconds: normal readings establish a baseline.'],['2','Trigger','Critical / missing / ML scenarios change at 15 seconds.'],['3','Interrupt','Disconnect during the incident. Acknowledge locally.'],['4','Recover','Restore the cloud. Inspect event IDs and acknowledgements.']].map(([n,t,d])=><div key={n}><b>{n}</b><strong>{t}</strong><p>{d}</p></div>)}</div></div>;
}
